### ISSUE TITLE
All the text in the settings and in the app picker is too light

### ISSUE THREAD

**Issue by realleok** [jeremyperkin/protonmail_themes#1]
What should I change to make it actually distinguishable?

**Comment by realleok** [comment]
This is for the Gmail Beta theme. Also, it causes emails with HTML to change their color to a navy and break into segments

**Comment by jeremyperkin** [comment]
any chance that you could provide a screenshot?

As I am unable to figure out what you mean about the text being too light.   As it seems fine on my 2 systems.  In both light and dark mode.

thanks in advance.

**Comment by realleok** [comment]
<img width="1486" alt="Screen Shot 2020-07-08 at 5 11 42 PM" src="https://user-images.githubusercontent.com/43764971/86970881-29b3be00-c13e-11ea-881a-fca1c3a3762d.png">
<img width="1481" alt="Screen Shot 2020-07-08 at 5 11 02 PM" src="https://user-images.githubusercontent.com/43764971/86970890-320bf900-c13e-11ea-8e33-0c82730a72e8.png">
<img width="594" alt="Screen Shot 2020-07-08 at 5 10 39 PM" src="https://user-images.githubusercontent.com/43764971/86970899-37694380-c13e-11ea-9f96-bd07024d40b8.png">
<img width="1484" alt="Screen Shot 2020-07-08 at 5 10 26 PM" src="https://user-images.githubusercontent.com/43764971/86970900-389a7080-c13e-11ea-9150-d3450bae1922.png">

Here are some screenshots, the first two showing what happens to a formatted email

**Comment by jeremyperkin** [comment]
@realleok are you running the latest code for the theme?

As I switched from the dark mode that I was running - light mode seems to a bit different from what you have shown me.   

Can you grab the latest code.  Make sure to copy your image line though.  Just so you do not lose the image and have to search for it again.   (I made the mistake myself :) )

**Comment by jeremyperkin** [comment]
@realleok Faded text should now be fixed.   Give it a try with the updated code.

**Comment by realleok** [comment]
Thanks for fixing, it seems to work well except for the app drop down is too light still. Little things i know. Also that HTML formatting glitch is still happening. Is there a way to leave the Email content alone? Thanks!

**Comment by jeremyperkin** [comment]
I just updated the HTML - update code please.

**Comment by realleok** [comment]
Everything works well now, thank you so much. If possible the app dropdown would be nice to change, but its very minor. Thanks for your hard work

**Comment by jeremyperkin** [comment]
@realleok Corrected the App Dropdown.  Take a look and let me know if it's working now for you.

**Comment by realleok** [comment]
Perfect, thanks for all the fixes!

**Comment by jeremyperkin** [comment]
Thanks for taking the time to notify me about these issues!

If there is anything else ever, let me know.
